server.port=8888
spring.cloud.config.server.git.uri=https://github.com/807037736/configServer-demo
spring.cloud.config.server.git.username=807037736@qq.com
spring.cloud.config.server.git.password=wy807037736
# 配置文件分支
spring.cloud.config.server.git.default-label=master
# 配置文件所在根目录
spring.cloud.config.server.git.search-paths=config
